# Generated by Django 4.1.6 on 2023-02-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbols',
            options={'verbose_name_plural': 'Symbols'},
        ),
    ]
