# Generated by Django 4.1.6 on 2023-02-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('server', '0002_alter_symbols_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.symbols')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
            options={
                'verbose_name_plural': 'Compamies Follow',
            },
        ),
    ]
