# Generated by Django 4.1.6 on 2023-02-07 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0003_companiesfollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companiesfollow',
            options={'verbose_name_plural': 'Companies Follow'},
        ),
        migrations.AlterField(
            model_name='companiesfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
